Repository qin-todo-e-team/qin_gorilla_todo, pull requests merged in 2022-02, with the labels that each got.

#9 feat: storybook導入
  .eslintrc.js
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/component/ExampleButton/Button.stories.tsx
  src/component/ExampleButton/Button.tsx
  src/component/ExampleButton/button.css
  yarn.lock
Labels: feature

#11 feat: github PR テンプレート導入
  .github/PULL_REQUEST_TEMPLATE.md
  .vscode/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#17 feat: firebase emulator導入
  .firebaserc
  .gitignore
  README.md
  firebase.json
  firestore.indexes.json
  firestore.rules
  package.json
Labels: enhancement

#19 feat: モデルを作成
  src/models/Todo.ts
  src/models/User.ts
Labels: feature

#22 build: firebaseインストール
  package.json
  yarn.lock
Labels: feature

#33 feat: firebase-react-hooks導入
  package.json
  yarn.lock
Labels: enhancement

#31 feat: テーマ登録の下地作成
  pages/_app.tsx
  pages/about.tsx
  pages/account/[userId]/theme/index.tsx
  pages/index.tsx
  src/component/theme/SelectRow/index.tsx
  src/component/theme/Theme.tsx
  src/component/theme/index.tsx
  src/repository/theme/themeCollection.ts
  src/repository/theme/useTheme.ts
  tsconfig.json
Labels: feature

#36 feat: テーマのレイアウト修正
  .eslintrc.js
  pages/account/[userId]/theme/index.tsx
  src/component/Layout/setting/index.tsx
  src/component/SettingTitle/index.tsx
  src/component/theme/SelectRow/index.tsx
  src/component/theme/Theme.tsx
  src/repository/theme/themeCollection.ts
  src/repository/theme/themeDoc.ts
  src/repository/theme/useTheme.ts
Labels: feature

#35 feat: ログイン機能実装
  .eslintrc.js
  config/firebase.ts
  package.json
  pages/_app.tsx
  pages/login.tsx
  src/pages/login/index.tsx
  yarn.lock
Labels: feature

#38 fix: テーマの取得の方法を修正
  src/component/theme/SelectRow/index.tsx
  src/repository/theme/useTheme.ts
Labels: fix

#20 feat: PostPanelを作成、ロゴ変更
  src/component/Panel/PostButton.stories.tsx
  src/component/Panel/PostButton.tsx
  src/component/Panel/PostPanel.tsx
  src/component/Panel/PostTextBox.stories.tsx
  src/component/Panel/PostTextBox.tsx
  src/pages/index/index.tsx
Labels: feature

#40 feat: PostPanelからfirebaseにTodoを追加する機能を実装
  src/component/Panel/PostPanel.tsx
  src/lib/getExpireDate.ts
  src/repository/todo/todoCollection.ts
  src/repository/todo/useTodo.ts
  tsconfig.json
Labels: feature

#37 Feat: Todoボタンの修正
  src/component/CheckBox/CheckBox.tsx
  src/component/RadioButton/RadioButton.tsx
  src/component/RadioButton/index.ts
  src/component/TodoList/TodoList.tsx
  src/pages/index/index.tsx
Labels: feature

#42 feat: アカウント設定のUI実装
  .eslintrc.js
  config/firebase.ts
  pages/_app.tsx
  pages/account/[userId]/accountSetting/index.tsx
  src/component/accountSetting/AccountSetting.tsx
  src/component/accountSetting/SelectRow/index.tsx
  src/component/accountSetting/index.tsx
Labels: feature
