Repository qin-todo-e-team/qin_gorilla_todo, pull requests merged in 2022-03, with the labels that each got.

#43 feat: ログアウト及びアカウント削除機能実装
  config/firebase.ts
  pages/_app.tsx
  src/component/accountSetting/AccountSetting.tsx
  src/context/AuthContext.tsx
  src/pages/login/index.tsx
Labels: feature

#44 feat: テーマ切り替え実装
  .eslintrc.js
  pages/_app.tsx
  pages/account/[userId]/theme/index.tsx
  src/component/Theme/SelectRow/index.tsx
  src/component/Theme/Theme.tsx
  src/component/Theme/index.tsx
  src/pages/account/[userId]/theme/index.tsx
  src/provider/ThemeProvider.tsx
Labels: feature

#45 feat: system colorを選べる実装
  config/theme.ts
  pages/_document.tsx
  src/component/Theme/SelectRow/index.tsx
  src/lib/setThemeColor.ts
  src/provider/ThemeProvider.tsx
Labels: feature

#52 feat: PostPanelをダークモード対応 #3
  src/component/Panel/PostPanel.tsx
Labels: feature

#53 refactor: ディレクトリ構成の変更
  pages/[userId]/account/accountSetting/index.tsx
  pages/[userId]/account/theme/index.tsx
  src/pages/[userId]/account/theme/index.tsx
Labels: refactor

#54 refactor: テーマをModelとして切り出し
  .eslintrc.js
  src/component/Theme/Theme.tsx
  src/models/Theme.ts
Labels: refactor

#51 feat: Todoページ作成 #47
  pages/[userId]/todo/index.tsx
  src/pages/[userId]/todo/index.tsx
Labels: feature

#56 fix: PostPanelの修正
  src/pages/[userId]/todo/index.tsx
Labels: fix

#63 feat: ログイン後のリダイレクト処理実装
  config/firebase.ts
  pages/index.tsx
  pages/login.tsx
  pages/myPage.tsx
  src/component/accountSetting/AccountSetting.tsx
  src/context/AuthContext.tsx
  src/hooks/useRequireLogin.tsx
  src/pages/login/index.tsx
Labels: feature

#69 feat: react-hot-toastの導入 #68
  package.json
  src/component/Theme/SelectRow/index.tsx
  src/pages/[userId]/account/profile/index.tsx
  src/pages/[userId]/account/theme/index.tsx
  src/pages/[userId]/todo/index.tsx
  src/repository/profile/useProfile.ts
  src/repository/toast/useToast.ts
  src/repository/todo/useTodo.ts
  yarn.lock
Labels: feature

#72 feat: スナックバーの表示位置を下から上に変更
  src/repository/toast/useToast.ts
Labels: feature

#73 feat: release-drafter追加
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: feature

#75 feat: todoContext追加（下地のみ）
  src/component/CheckBox/CheckBox.tsx
  src/component/Panel/PostPanel.tsx
  src/component/TodoList/TodoList.tsx
  src/context/TodoContext.tsx
  src/lib/TodoFilter.ts
  src/pages/[userId]/todo/index.tsx
  tsconfig.json
Labels: feature

#78 fix: themeのエラーハンドリング
  src/component/Theme/SelectRow/index.tsx
Labels: fix

#79 fix: commitのtitleでもラベルがつくように修正
  .github/release-drafter.yml
Labels: fix

#77 fix: TodoFilterで正常に分類されない問題に対応
  src/lib/TodoFilter.ts
Labels: fix, bug

#76 fix: アカウントの削除後に画面遷移しない問題に対応
  config/firebase.ts
  src/component/accountSetting/AccountSetting.tsx
Labels: fix, bug
